version: '3.3'
services:
  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: pgsql_container
    image: postgres:13.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
    postgres_data:

#  version: '3.3'
# services:
#   db:
#     container_name: pgsql_container
#     image: postgres:13.4-alpine
#     restart: always
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: lavka_app_db
#     ports:
#       - "5432:5432"

#   backend:
#     image: davletelvir/lavka_app:latest
#     restart: always
#     depends_on:
#       - db

# volumes:
#   postgres_data: