version: '3.3'
services:
  db:
    container_name: pgsql_container
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lavka_app_db
    ports:
      - "5432:5432"

  backend:
    image: davletelvir/test_lavka_app:latest
    restart: always
    ports:
     - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data: